/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.ProductoJpaController;
import control.exceptions.NonexistentEntityException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;

/**
 *
 * @author alega
 */
public class Inventario extends javax.swing.JFrame {

    /**
     * Creates new form Inventarioj
     */
    private Producto producto;
    private EntityManagerFactory emf;
    private ProductoJpaController pjc;
    private String estadoBoton = null;
    private int codigo;
    
    public Inventario() {
        initComponents();
        setLocationRelativeTo(null);
        inicio();
        visualizar();
    }
    
    public void visualizar(){
        codigoTxt.setVisible(false);
        buscarBoton.setVisible(false);
        nombreLabel.setVisible(false);
        nombreCombo.setVisible(false);
        codigoLabel.setVisible(false);
    }
    
    public void iniciarControlador(){
        emf = Persistence.createEntityManagerFactory("NanoSystemPU");
        pjc = new ProductoJpaController(emf);
    }
    
    public void inicio (){
        aceptarBoton.setVisible(false);
        cancelarBoton.setVisible(false);
        
        nombreTxt.setEditable(false);
        descripcionTxt.setEditable(false);
        fabricanteTxt.setEditable(false);
        marcaTxt.setEditable(false);
        precioTxt.setEditable(false);
    }
    
    public void actualizarTabla(){
        this.setVisible(false);
        Inventario invAux = new Inventario();
        invAux.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        NanoSystemPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("NanoSystemPU").createEntityManager();
        productoQuery = java.beans.Beans.isDesignTime() ? null : NanoSystemPUEntityManager.createQuery("SELECT p FROM Producto p");
        productoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : productoQuery.getResultList();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        nombreTxt = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripcionTxt = new javax.swing.JTextArea();
        jTextField6 = new javax.swing.JTextField();
        fabricanteTxt = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        marcaTxt = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        precioTxt = new javax.swing.JTextField();
        aceptarBoton = new javax.swing.JButton();
        cancelarBoton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProducto = new javax.swing.JTable();
        codigoLabel = new javax.swing.JLabel();
        codigoTxt = new javax.swing.JTextField();
        buscarBoton = new javax.swing.JButton();
        nombreLabel = new javax.swing.JLabel();
        nombreCombo = new javax.swing.JComboBox();
        editar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        agregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/font.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 900));

        jTextField1.setBackground(new java.awt.Color(51, 51, 51));
        jTextField1.setFont(new java.awt.Font("Haettenschweiler", 0, 48)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("INVENTARIO");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 51, 59));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(51, 51, 59));
        jTextField3.setFont(new java.awt.Font("Eras Light ITC", 1, 16)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 0, 0));
        jTextField3.setText(" Nombre");
        jTextField3.setBorder(null);

        nombreTxt.setBackground(new java.awt.Color(51, 51, 51));
        nombreTxt.setFont(new java.awt.Font("Eras Light ITC", 0, 16)); // NOI18N
        nombreTxt.setForeground(new java.awt.Color(204, 204, 204));
        nombreTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombreTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(51, 51, 59));
        jTextField4.setFont(new java.awt.Font("Eras Light ITC", 1, 16)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(0, 0, 0));
        jTextField4.setText(" Descripción");
        jTextField4.setBorder(null);

        descripcionTxt.setBackground(new java.awt.Color(51, 51, 51));
        descripcionTxt.setColumns(20);
        descripcionTxt.setFont(new java.awt.Font("Eras Light ITC", 0, 16)); // NOI18N
        descripcionTxt.setForeground(new java.awt.Color(204, 204, 204));
        descripcionTxt.setRows(5);
        descripcionTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane2.setViewportView(descripcionTxt);

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(51, 51, 59));
        jTextField6.setFont(new java.awt.Font("Eras Light ITC", 1, 16)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(0, 0, 0));
        jTextField6.setText(" Fabricante");
        jTextField6.setBorder(null);

        fabricanteTxt.setBackground(new java.awt.Color(51, 51, 51));
        fabricanteTxt.setFont(new java.awt.Font("Eras Light ITC", 0, 16)); // NOI18N
        fabricanteTxt.setForeground(new java.awt.Color(204, 204, 204));
        fabricanteTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fabricanteTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(51, 51, 59));
        jTextField8.setFont(new java.awt.Font("Eras Light ITC", 1, 16)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(0, 0, 0));
        jTextField8.setText(" Marca");
        jTextField8.setBorder(null);

        marcaTxt.setBackground(new java.awt.Color(51, 51, 51));
        marcaTxt.setFont(new java.awt.Font("Eras Light ITC", 0, 16)); // NOI18N
        marcaTxt.setForeground(new java.awt.Color(204, 204, 204));
        marcaTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        marcaTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(51, 51, 59));
        jTextField10.setFont(new java.awt.Font("Eras Light ITC", 1, 16)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(0, 0, 0));
        jTextField10.setText(" Precio");
        jTextField10.setBorder(null);
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        precioTxt.setBackground(new java.awt.Color(51, 51, 51));
        precioTxt.setFont(new java.awt.Font("Eras Light ITC", 0, 16)); // NOI18N
        precioTxt.setForeground(new java.awt.Color(204, 204, 204));
        precioTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        precioTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        aceptarBoton.setBackground(new java.awt.Color(51, 51, 51));
        aceptarBoton.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        aceptarBoton.setForeground(new java.awt.Color(0, 0, 0));
        aceptarBoton.setText("Aceptar");
        aceptarBoton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        aceptarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBotonActionPerformed(evt);
            }
        });

        cancelarBoton.setBackground(new java.awt.Color(51, 51, 51));
        cancelarBoton.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        cancelarBoton.setForeground(new java.awt.Color(0, 0, 0));
        cancelarBoton.setText("Cancelar");
        cancelarBoton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cancelarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(precioTxt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(marcaTxt))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(189, 189, 189))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(fabricanteTxt))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nombreTxt))))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(aceptarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fabricanteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marcaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(165, 165, 165))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, 370, 840));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, productoList, tablaProducto);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codigoProducto}"));
        columnBinding.setColumnName("Codigo Producto");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nombre}"));
        columnBinding.setColumnName("Nombre");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${descripcion}"));
        columnBinding.setColumnName("Descripcion");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fabricante}"));
        columnBinding.setColumnName("Fabricante");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${marca}"));
        columnBinding.setColumnName("Marca");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${precio}"));
        columnBinding.setColumnName("Precio");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        tablaProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                holaAA(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProducto);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 740, 610));

        codigoLabel.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
        codigoLabel.setForeground(new java.awt.Color(204, 204, 204));
        codigoLabel.setText("Código");
        jPanel2.add(codigoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        codigoTxt.setBackground(new java.awt.Color(51, 51, 51));
        codigoTxt.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        codigoTxt.setForeground(new java.awt.Color(204, 204, 204));
        codigoTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(codigoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 170, -1));

        buscarBoton.setBackground(new java.awt.Color(51, 51, 51));
        buscarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        jPanel2.add(buscarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 30, 40));

        nombreLabel.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
        nombreLabel.setForeground(new java.awt.Color(204, 204, 204));
        nombreLabel.setText("Nombre del producto");
        jPanel2.add(nombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, -1));

        nombreCombo.setBackground(new java.awt.Color(51, 51, 51));
        nombreCombo.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        nombreCombo.setForeground(new java.awt.Color(204, 204, 204));
        nombreCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(nombreCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 220, -1));

        editar.setBackground(new java.awt.Color(51, 51, 51));
        editar.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        editar.setForeground(new java.awt.Color(0, 0, 0));
        editar.setText("Editar");
        editar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        jPanel2.add(editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 810, 80, 40));

        eliminar.setBackground(new java.awt.Color(51, 51, 51));
        eliminar.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        eliminar.setForeground(new java.awt.Color(0, 0, 0));
        eliminar.setText("   Eliminar");
        eliminar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jPanel2.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 810, 110, 40));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuprincipal.png"))); // NOI18N
        jButton1.setText("   Regresar al menú gerencia");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 3, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 810, 270, 50));

        agregar.setBackground(new java.awt.Color(51, 51, 51));
        agregar.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        agregar.setForeground(new java.awt.Color(0, 0, 0));
        agregar.setText("Agregar");
        agregar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        jPanel2.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 810, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        NavegacionGerencia ng = new NavegacionGerencia();
        ng.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void camposEditables(){
        nombreTxt.setEditable(true);
        descripcionTxt.setEditable(true);
        fabricanteTxt.setEditable(true);
        marcaTxt.setEditable(true);
        precioTxt.setEditable(true);
    }
    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        // TODO add your handling code here:
        int fila = tablaProducto.getSelectedRow();
        if(fila<0)
            JOptionPane.showMessageDialog(null,"Antes seleccione una fila");
        else{
            camposEditables();
            aceptarBoton.setVisible(true);
            cancelarBoton.setVisible(true);
            estadoBoton = "editar";
        }
    }//GEN-LAST:event_editarActionPerformed

    private void cancelarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBotonActionPerformed
        // TODO add your handling code here:
        nombreTxt.setText("");
        nombreTxt.setEditable(false);
        descripcionTxt.setText("");
        descripcionTxt.setEditable(false);
        fabricanteTxt.setText("");
        fabricanteTxt.setEditable(false);
        marcaTxt.setText("");
        marcaTxt.setEditable(false);
        precioTxt.setText("");
        precioTxt.setEditable(false);
        
        aceptarBoton.setVisible(false);
        cancelarBoton.setVisible(false);
    }//GEN-LAST:event_cancelarBotonActionPerformed

    private void holaAA(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_holaAA
        // TODO add your handling code here:
        int fila = tablaProducto.getSelectedRow();
        nombreTxt.setText(tablaProducto.getValueAt(fila,1).toString());
        descripcionTxt.setText(tablaProducto.getValueAt(fila,2).toString());
        fabricanteTxt.setText(tablaProducto.getValueAt(fila,3).toString());
        marcaTxt.setText(tablaProducto.getValueAt(fila,4).toString());
        precioTxt.setText(tablaProducto.getValueAt(fila,5).toString());
    }//GEN-LAST:event_holaAA

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        int fila = tablaProducto.getSelectedRow();
        if(fila>0){
            if(JOptionPane.showConfirmDialog(null,"¿Está seguro que desea eliminar: "+tablaProducto.getValueAt(fila, 2)+"?","",JOptionPane.YES_NO_OPTION)==0){
                JOptionPane.showMessageDialog(null,tablaProducto.getValueAt(fila, 2) + " eliminado");
                iniciarControlador();
                try {
                    pjc.destroy(Integer.parseInt(tablaProducto.getValueAt(fila,0).toString()));
                } catch (NonexistentEntityException ex) {
                    Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
                }
                actualizarTabla();
            } 
        }
        else
            JOptionPane.showMessageDialog(null,"Primero seleccione una fila");
    }//GEN-LAST:event_eliminarActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        aceptarBoton.setVisible(true);
        cancelarBoton.setVisible(true);

        marcaTxt.setText(null);
        nombreTxt.setText(null);
        precioTxt.setText(null);
        fabricanteTxt.setText(null);
        descripcionTxt.setText(null);
        
        marcaTxt.setEditable(true);
        nombreTxt.setEditable(true);
        precioTxt.setEditable(true);
        fabricanteTxt.setEditable(true);
        descripcionTxt.setEditable(true);
        
        estadoBoton = "agregar";
    }//GEN-LAST:event_agregarActionPerformed

    private void aceptarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBotonActionPerformed
        // TODO add your handling code here
        
        if(estadoBoton.equals("agregar")){
            
            producto = new Producto();
            producto.setMarca(marcaTxt.getText());
            producto.setNombre(nombreTxt.getText());
            producto.setFabricante(fabricanteTxt.getText());
            producto.setDescripcion(descripcionTxt.getText());
            producto.setPrecio(Integer.parseInt(precioTxt.getText()));
            
            iniciarControlador();
            pjc.create(producto);
            JOptionPane.showMessageDialog(null,"Producto "+nombreTxt.getText()+" agregado correctamente");
            actualizarTabla();
        }
        
        else if(estadoBoton.equals("editar")){
            codigo = Integer.parseInt(tablaProducto.getValueAt(tablaProducto.getSelectedRow(),0).toString());
            
            iniciarControlador();
            producto = pjc.findProducto(codigo);
            producto.setMarca(marcaTxt.getText());
            producto.setNombre(nombreTxt.getText());
            producto.setFabricante(fabricanteTxt.getText());
            producto.setDescripcion(descripcionTxt.getText());
            producto.setPrecio(Integer.parseInt(precioTxt.getText()));
            
            try {
                pjc.edit(producto);
            } catch (Exception ex) {
                Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            JOptionPane.showMessageDialog(null,"Producto "+nombreTxt.getText()+" editado correctamente");
            actualizarTabla();
        }
        
        
        aceptarBoton.setVisible(false);
        cancelarBoton.setVisible(false);
    }//GEN-LAST:event_aceptarBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager NanoSystemPUEntityManager;
    private javax.swing.JButton aceptarBoton;
    private javax.swing.JButton agregar;
    private javax.swing.JButton buscarBoton;
    private javax.swing.JButton cancelarBoton;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JTextField codigoTxt;
    private javax.swing.JTextArea descripcionTxt;
    private javax.swing.JButton editar;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField fabricanteTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField marcaTxt;
    private javax.swing.JComboBox nombreCombo;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JTextField precioTxt;
    private java.util.List<modelo.Producto> productoList;
    private javax.persistence.Query productoQuery;
    private javax.swing.JTable tablaProducto;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
