/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alega
 */
public class VendedorVista extends javax.swing.JFrame {

    /**
     * Creates new form VendedorVista
     */
    private Extra extra = new Extra();
    private double subTotalN=0, ivaN=0, totalN=0;
    public VendedorVista() {
        initComponents();
        setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        NanoSystemPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("NanoSystemPU").createEntityManager();
        productoQuery = java.beans.Beans.isDesignTime() ? null : NanoSystemPUEntityManager.createQuery("SELECT p FROM Producto p");
        productoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : productoQuery.getResultList();
        ticketEncabezado = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        totalTxt = new javax.swing.JTextField();
        subotal = new javax.swing.JTextField();
        subtotalTxt = new javax.swing.JTextField();
        iva = new javax.swing.JTextField();
        ivaTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTicket = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        codigoTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProducto = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        agregarBoton = new javax.swing.JButton();
        cancelarProdBoton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        buscarBoton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NANO SYSTEM");
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1300, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ticketEncabezado.setEditable(false);
        ticketEncabezado.setBackground(new java.awt.Color(51, 51, 51));
        ticketEncabezado.setFont(new java.awt.Font("Eras Light ITC", 0, 24)); // NOI18N
        ticketEncabezado.setForeground(new java.awt.Color(204, 204, 204));
        ticketEncabezado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ticketEncabezado.setText("TICKET");
        ticketEncabezado.setBorder(null);
        getContentPane().add(ticketEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 100, 270, 30));

        total.setEditable(false);
        total.setBackground(new java.awt.Color(51, 51, 51));
        total.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
        total.setForeground(new java.awt.Color(204, 204, 204));
        total.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        total.setText("Total");
        total.setBorder(null);
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 680, 120, 30));

        totalTxt.setEditable(false);
        totalTxt.setBackground(new java.awt.Color(51, 51, 51));
        totalTxt.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(totalTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 680, 200, 30));

        subotal.setEditable(false);
        subotal.setBackground(new java.awt.Color(51, 51, 51));
        subotal.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
        subotal.setForeground(new java.awt.Color(204, 204, 204));
        subotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        subotal.setText("Subtotal");
        subotal.setBorder(null);
        subotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subotalActionPerformed(evt);
            }
        });
        getContentPane().add(subotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 580, 120, 30));

        subtotalTxt.setEditable(false);
        subtotalTxt.setBackground(new java.awt.Color(51, 51, 51));
        subtotalTxt.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(subtotalTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 580, 200, 30));

        iva.setEditable(false);
        iva.setBackground(new java.awt.Color(51, 51, 51));
        iva.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
        iva.setForeground(new java.awt.Color(204, 204, 204));
        iva.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iva.setText("I.V.A");
        iva.setBorder(null);
        iva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ivaActionPerformed(evt);
            }
        });
        getContentPane().add(iva, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 630, 120, 30));

        ivaTxt.setEditable(false);
        ivaTxt.setBackground(new java.awt.Color(51, 51, 51));
        ivaTxt.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(ivaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 630, 200, 30));

        tablaTicket.setBackground(new java.awt.Color(51, 51, 51));
        tablaTicket.setForeground(new java.awt.Color(204, 204, 204));
        tablaTicket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaTicket.setGridColor(new java.awt.Color(51, 51, 51));
        tablaTicket.setSelectionBackground(new java.awt.Color(0, 153, 153));
        tablaTicket.setSelectionForeground(new java.awt.Color(255, 255, 0));
        jScrollPane1.setViewportView(tablaTicket);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 160, 330, 390));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/font.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, 392, 699));

        jLabel2.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Nombre del producto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        codigoTxt.setBackground(new java.awt.Color(51, 51, 51));
        codigoTxt.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        codigoTxt.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(codigoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 170, -1));

        jLabel3.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Código");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(51, 51, 51));
        jComboBox1.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(204, 204, 204));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 220, -1));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, productoList, tablaProducto);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codigoProducto}"));
        columnBinding.setColumnName("Codigo Producto");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nombre}"));
        columnBinding.setColumnName("Nombre");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${descripcion}"));
        columnBinding.setColumnName("Descripcion");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${marca}"));
        columnBinding.setColumnName("Marca");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fabricante}"));
        columnBinding.setColumnName("Fabricante");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${precio}"));
        columnBinding.setColumnName("Precio");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane2.setViewportView(tablaProducto);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 790, -1));

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Haettenschweiler", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("NANO SYSTEM");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 210, 60));

        agregarBoton.setBackground(new java.awt.Color(51, 51, 51));
        agregarBoton.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        agregarBoton.setForeground(new java.awt.Color(0, 0, 0));
        agregarBoton.setText("   Agregar producto seleccionado   ");
        agregarBoton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        agregarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBotonActionPerformed(evt);
            }
        });
        getContentPane().add(agregarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 670, -1, 40));

        cancelarProdBoton.setBackground(new java.awt.Color(51, 51, 51));
        cancelarProdBoton.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        cancelarProdBoton.setForeground(new java.awt.Color(0, 0, 0));
        cancelarProdBoton.setText("   Cancelar producto seleccionado   ");
        cancelarProdBoton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cancelarProdBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarProdBotonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelarProdBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 670, 230, 40));

        jPanel1.setBackground(new java.awt.Color(6, 34, 56));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 3, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuprincipal.png"))); // NOI18N
        jButton1.setText("   Regresar al menú principal");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 3, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 270, 50));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cobro.png"))); // NOI18N
        jButton3.setText("   Cobrar Compra");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 3, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 190, 50));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        jButton2.setText("   Cancelar compra");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 3, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 210, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 770, 1030, 70));

        buscarBoton.setBackground(new java.awt.Color(51, 51, 51));
        buscarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        buscarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBotonActionPerformed(evt);
            }
        });
        getContentPane().add(buscarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 30, 40));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 900));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void subotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subotalActionPerformed

    private void ivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ivaActionPerformed

    private void cancelarProdBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarProdBotonActionPerformed
        // TODO add your handling code here:
        
        int fila = tablaTicket.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel) tablaTicket.getModel();
        if(fila>=0){
            subTotalN = subTotalN-Integer.parseInt(tablaTicket.getValueAt(fila,2).toString());
            ivaN = subTotalN * .16;
            totalN = subTotalN + ivaN;
            subtotalTxt.setText("$ "+String.format("%.2f", subTotalN));
            ivaTxt.setText("$ "+String.format("%.2f", ivaN));
            totalTxt.setText("$ "+String.format("%.2f", totalN));
            dtm.removeRow(fila);
        }
    }//GEN-LAST:event_cancelarProdBotonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        VistaPrincipal vp = new VistaPrincipal();
        vp.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        subtotalTxt.setText("");
        ivaTxt.setText("");
        totalTxt.setText("");
        subTotalN = 0;
        ivaN = 0;
        totalN = 0;
        DefaultTableModel dtm = (DefaultTableModel) tablaTicket.getModel();
        extra.borrarTabla(dtm);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void agregarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBotonActionPerformed
        // TODO add your handling code here:
        int fila = tablaProducto.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel) tablaTicket.getModel();
        if(fila<0)
            JOptionPane.showMessageDialog(null,"Antes seleccione una fila");
        else{
            Object [] newRow = {tablaProducto.getValueAt(fila,0),tablaProducto.getValueAt(fila,2),tablaProducto.getValueAt(fila,5)};
            dtm.addRow(newRow);
            subTotalN = subTotalN+Integer.parseInt(tablaProducto.getValueAt(fila,5).toString());
            ivaN = subTotalN * .16;
            totalN = subTotalN + ivaN;
            subtotalTxt.setText("$ "+String.format("%.2f", subTotalN));
            ivaTxt.setText("$ "+String.format("%.2f", ivaN));
            totalTxt.setText("$ "+String.format("%.2f", totalN));
        }
    }//GEN-LAST:event_agregarBotonActionPerformed

    private void buscarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBotonActionPerformed
        // TODO add your handling code here:
        //int cod = Integer.parseInt(codigoTxt.getText());
        //DefaultTableModel dtm = (DefaultTableModel) tablaProducto.getModel();
        //extra.borrarTabla(dtm);
        JOptionPane.showMessageDialog(null,"Estamos trabajando en esto");
    }//GEN-LAST:event_buscarBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendedorVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendedorVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendedorVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendedorVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendedorVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager NanoSystemPUEntityManager;
    private javax.swing.JButton agregarBoton;
    private javax.swing.JButton buscarBoton;
    private javax.swing.JButton cancelarProdBoton;
    private javax.swing.JTextField codigoTxt;
    private javax.swing.JTextField iva;
    private javax.swing.JTextField ivaTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.util.List<modelo.Producto> productoList;
    private javax.persistence.Query productoQuery;
    private javax.swing.JTextField subotal;
    private javax.swing.JTextField subtotalTxt;
    private javax.swing.JTable tablaProducto;
    private javax.swing.JTable tablaTicket;
    private javax.swing.JTextField ticketEncabezado;
    private javax.swing.JTextField total;
    private javax.swing.JTextField totalTxt;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
